### ISSUE TITLE
Speaker workaround causes low volume on headphone jack

### ISSUE THREAD

**Issue by kwistbac** [droserasprout/lenovo-yoga-c930-linux#1]
I have noticed that the speaker workaround (pin 0x17 override to dock headphone) causes low volume on the headphone jack. Are you able to confirm this?

**Comment by droserasprout** [comment]
Did not check this one yet, but it's most likely possible. I'll add a note to this workaround.

I've spent some time with hdajackretask and hda-analyzer tuning pin configuration and failed to find any logic behind it (as well as to find any configuration to make bottom speakers and internal mic work). But yes, some nodes' volume affect another ones'. We need to [file a bug in ALSA](https://alsa-project.org/main/index.php/Bug_Tracking) to get some qualified help. But there are some things I want to make clear with ACPI and power management first.
