### ISSUE TITLE
C930 S0ix power bug seems to be fixed in kernels 5.3 and newer

### ISSUE THREAD

**Issue by Cubevoid** [droserasprout/lenovo-yoga-c930-linux#4]
According to https://bugzilla.kernel.org/show_bug.cgi?id=203383#c6, 

> This issue appears to be fixed in kernel 5.3.x. 
> 
> Testing with kernel 5.3.8 gives the following results:
> 
> ```
> $ cat /sys/kernel/debug/dri/0/i915_dmc_info
> fw loaded: yes
> path: i915/kbl_dmc_ver1_04.bin
> version: 1.4
> DC3 -> DC5 count: 5467
> DC5 -> DC6 count: 5450
> program base: 0x09004040
> ssp base: 0x00002fc0
> htp: 0x00b40068
> 
> $ cat /sys/devices/system/cpu/cpuidle/low_power_idle_system_residency_us
> 30924410855
> 
> 
> Power drain while sleeping:
> 
> start second: 1573428215
>   end second: 1573458324
> time consumed: 30109 seconds
> 
> start energy: 42.39 Wh
>   end energy: 40.43 Wh
> energy consumed: 1.96 Wh
> 
> watts used while asleep = .23434853366103158524
```
> 
> Testing with kernel 5.2.21 gives the same results as previously posted by drsrsprt.

**Comment by droserasprout** [comment]
Thanks for your contribution! I've added you to collaborators if you would like to keep notes in this repo up to date. I have already sell this laptop and have neither ability nor personal interest in this.
